### ISSUE TITLE
I am looking to run a discord bot with this code and I am unsure where to start?

### ISSUE THREAD

**Issue by immason29** [0xRaptor/erlc#2]
Hello! So I have successfully added both this repo and Discord.js into my Repository for the ER:LC bot, I am looking to find a way to get my discord bot to function with this code and I am not sure exactly how, maybe someone else has more information on this but I have seen many discord bots using this type of code and I am not exactly sure where to start to link discord and this to make a command.

**Comment by 0xRaptor** [comment]
Examples of usage of the library can be found in the docs. If you are looking to create a discord bot command this is the wrong place to ask you should ask discord.js or whatever library you are using.

**Comment by sspccreates** [comment]
I understand and I have figured that part out, I was wondering if there was a way to integrate the in-game logs with Discord.js and how would I be able to do that? Or maybe mod-calls to send a message to a channel, that's what I am looking for maybe in a webhook?

**Comment by immason29** [comment]
> Examples of usage of the library can be found in the docs. If you are looking to create a discord bot command this is the wrong place to ask you should ask discord.js or whatever library you are using.

I understand and I have figured that part out, I was wondering if there was a way to integrate the in-game logs with Discord.js and how would I be able to do that? Or maybe mod-calls to send a message to a channel, that's what I am looking for maybe in a webhook?
