### ISSUE TITLE
Discord Bot Support (continued)

### ISSUE THREAD

**Issue by immason29** [0xRaptor/erlc#3]
I was wondering if there was a way to integrate the in-game logs with Discord.js and how would I be able to do that? Or maybe mod-calls to send a message to a channel, that's what I am looking for maybe in a webhook?

**Comment by Exodo0** [comment]
I modified the NPM module a bit and what I got was this:
![image](https://github.com/user-attachments/assets/efb6a1e0-2921-4c08-9cd1-6336931e2683)
It shows you the Unanswered ModCalls, and among many other things it tells you how many staff members are on the server.
